# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('paid', models.PositiveIntegerField()),
                ('change', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('sub_total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sales.Order')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('base_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('stock_min', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='sales.Product'),
        ),
    ]
